### ISSUE TITLE
Disable logging for specific paths

### ISSUE THREAD

**Issue by dlozlla** [telefonicaid/logops#17]
I am using this library for an app that serves web pages. I am interested in logging the requests sent to my "functional" endpoints but I really don't want to log each and every request that the browser sends to get static content (images, css, javascript, etc). Would it be possible to disable logging for specific paths?

**Comment by palmerabollo** [comment]
Logops doesn't know anything about your app. It logs strings/objects in different levels (debug, info...) but it doesn't have any information about the specific service requirements.

Said that, I am also suffering the issue (logs becoming too verbose), but I think it should be solved in [node-express-logger](https://github.com/Telefonica/node-express-logging/) that is the module who logs the http requests.
