### ISSUE TITLE
Dynamic context properties

### ISSUE THREAD

**Issue by jmendiara** [telefonicaid/logops#7]
Allow not prefixed context properties

```js
logger.info({some: 'value'}, 'This is %s', 'Sparta');
// {"time":"2015-06-23T10:13:49.879Z","lvl":"INFO","some":"value","msg":"This is Sparta"}
```

Related to #5

**Comment by palmerabollo** [comment]
+1

**Comment by palmerabollo** [comment]
This doesn't break backwards compatibility (if you don't use additional properties everything works as usual) if anyone needs it before 1.x
